### ISSUE TITLE
Zeph's China event chains list

### ISSUE THREAD

**Issue by neothiamin** [Zephyrum/FoI#35]
#Zeph edit: All things in this thread are done but need playtesting.

![9e7823f7673e9c8be4cece57ae6d31ad](https://user-images.githubusercontent.com/8920936/66395359-39cb2100-e9a5-11e9-8be3-cf3882332396.png)

**Comment by Zephyrum** [comment]
who made this? what a brilliant dude

**Comment by Zephyrum** [comment]
Explaining the "details TBA" part:

_Yuan Succession Crisis_
Because I'm not creative enough for names right now, assume the Khagan is named Bob and his son Bobby

Bob is currently aged over 60, and is not a great ruler other than his military (2/0/5). He knows well enough that his court eunuchs are more than willing to pull his family out of the throne since his only living son is too young to do anything about it. And with a bunch of angry warlords down South, what can he do? Well, he'll need to pull off some things before he hit the sack if he wants to secure his succession. A decision can be taken if you accumulate a few global flags I'll be discussing soon.

To clarify, the following events have short MTTHs, and don't really have an order. They're virtually guaranteed to fire, though. In order to prevent fuckery, we grant Bob and Bobby the Immortal trait and murder them both by event.

The first one is to personally get involved in educating his son, Bobby. Bobby's education being centered around him means he has less time to focus on his country and his admin will drop by one point, furthermore he'll lose five prestige. Leaving Bobby to the usual court educators means you'll pay a small fee in ducats.

The second one is to make concessions to southern warlords. Bob can decide whether he wants to recognize their authority over their currently controlled regions, which, if he does, gives the warlords +10 prestige and +20 relations with Yuan, at the cost of 20 prestige and 15 legitimacy. Else, Bob can reaffirm his authority, gaining -10% aggressive expansion impact on himself for 50 years at the cost of -40 relations with all warlords.

The third one involves specifically the Jin. The Jin is a loyalist vassal at first, and Bob might want their help silencing the rivals. So, he can choose to request assistance from the warlord, granting him +10% manpower recovery for 50 years, at the cost of 10 prestige and a lump sum of ca$h. Well, Bob can also decide to demand their help, alienating them a bit - the modifier is doubled to +20%, lasts the same time, and has no prestige cost, plus a lessened ducat cost. Sounds too good to be true, but you also make the Jin like you some 20 relations points less.

The decision "Secure Bobby's Succession" requires you to have taken at least two of the above, will require you to have positive (1 or higher) Stability, as well as at least 20 prestige to spare. At the cost of -2 stability, -40 prestige, you can run a purge of the eunuch faction, kicking all the troublesome elements out. Yuan will receive +20% advisor cost, +10% aggressive expansion impact, +5% all power costs and -10% morale of armies for 40 years, leaving them slightly exposed, but this prevents the crisis from firing further (leftmost path - nerfed Yuan victory, crisis averted).

Bob will drop dead in 1460, at the ripe old age of "at least 75 lmao" by event, and it's intended that all relevant events here fire by then.

**Comment by Zephyrum** [comment]
Hot Chintato part 2 Tao Boogaloo:

Jin invited in and accepts:
The Yuan is kicked out of China without a fight. Jin takes over Beijing and the Northern China Region provinces owned by Yuan. Yuan is punted out, converts into Mongolia. The Ming then get an event to fight the Jin with a special CB which they can accept or not. Accepting it costs stability and pisses off by -20 all the warlords, pissing Jin off specially by -100. If Ming declines, happy emperoring, Jin.

Else, Yuan might remain in place. If the Ming decides to fight them, same thing as before, just that the -100 goes to Yuan. Oh, and of course, maybe the Yuan will get out unscathed if Ming pussies out!

I'd prefer if wars in this event - and wars in case the Ming refuse and they fight later - to be very conclusive. I'm not sure how much you guys are willing to go with this since it's somewhat railroady - tell me if it sucks, please - but figuring out a way to make sure it's a pretty heavy hit. If the Ming beats Jin, Jin would be fully annexed. If the Ming beats Yuan, they get North China and Yuan gets punted as usual. If either Jin or Yuan beats Ming, then Ming gets kicked out of all of their lands with the exception of a few Jianghuai cultured States around Nanjing, to be easily annexed later.

That all said and done, it would end the Northern China conflict... but the South is still open! And something might be forming in Moghulistan and Oirat... How will that go?!

**Comment by Zephyrum** [comment]
_Jacob Rees-Mogghulistan_ - Chagatexit from the Mongol Empire

-Yuan does not exist, but Mongolia does
-Is Moghulistan and Chagatai does not exist, or is Chagatai and Moghulistan does not exist
-Is independent or tributary

Option A: "Our brethren has failed, it's our time to rise!"
Gain claims on all of Oirat and Mongolia
-50 relations with Mongolia
-10 horde unity

Option B: "Let's content with keeping our family united."
-+50 relations with Mongolia
+10 horde unity

**Comment by Zephyrum** [comment]
![image](https://user-images.githubusercontent.com/3027827/66615433-0f46b700-eba3-11e9-8e67-15a08e158b15.png)
![image](https://user-images.githubusercontent.com/3027827/66615438-166dc500-eba3-11e9-8d93-6a9a6fc8e4f9.png)

**Comment by Zephyrum** [comment]
Qin's story

![image](https://user-images.githubusercontent.com/3027827/66615453-29809500-eba3-11e9-8a58-294d8fba1d2c.png)

**Comment by neothiamin** [comment]
Running list of problems with the chains above:

* Ming, or really any Yuan vassal, can declare an independence war at any time, potentially nullifying the whole chain. This is, in my opinion, a HUGE issue.
* Some of the localization is way too memey. For example, foi_yuan.5.b.
* The decision foi_yuan_secure_heir_succession still needs localization, as does its modifier.
* There is NO indication of which choices are the right ones to allow the succession crisis to be managed.
* The whole chain seems, erm, kind of... or maybe like REALLY easy? I'm not sure though, I need to do more runs.

Not necessarily a problem with the chains, but Ming has the decision "Call forth the Red Turbans" which I'm not sure should exist.

**Comment by Zephyrum** [comment]
One by one:
- My bad, I thought we removed Ming's vassalage? They shouldn't be a vassal at game start, so they can go wild on the South while the North is bickering, that's the point of the chains.
- No! No! No! No! NO! :(
- Fixed, thanks
- Intentional-ish. Since we added a way to fight back regardless of route, all results for Yuan can end well for a player at a point. Ming and Jin are given only a single decision to make each, so non-issue. I feel like the warning we gave is enough given that those events universally have a "better" option, and taking the "worse" option three times is the way to success.
- What do you mean by "easy"? It's supposed to be simple to navigate and code by design since I wanted to avoid flex taped design like the Asturias war, so I didn't get too fancy. Naturally this means it's over fairly soon, I guess.
- You can take it even at <20 prestige, including negative values, unless there is a trigger saying otherwise. In fact, at <-80, you lose less than 20. I don't see it being painful beside hurting osme national modifiers.

- The decision is legacy, yes. Removing it now on github.

**Comment by Zephyrum** [comment]
Missing playtesting, any takers?

**Comment by Zephyrum** [comment]
*lowkey assigns to Couch*

**Comment by Zephyrum** [comment]
Ding dong you're mister wrong go back to close
