### ISSUE TITLE
SEA Micropatch to-do

### ISSUE THREAD

**Issue by Zephyrum** [Zephyrum/FoI#41]
**Zeph edit: All of this is done except for integrating the start screens.**

_Reworked Malaccan Peninsula: #one of the IDs here is wrong, i fixed it but forgot which
697, 2392 -> to Perak (PRK)
597, 2686 -> to Johor (JOH)
JOH - Change flag, has star and crescent, is Theravada Malayan. Also make a vassal of MLC._

_Development of Javan provinces:
625 to 3/4/3
626 to 5/6/3
628 to 6/6/4
629 to 6/6/3
630 to 5/5/4
2687 to 5/5/3
2688 to 5/5/3
2689 to 3/4/3
2692 to 2/2/1_

_Cede to Majapahit: 623, 639, 640, 642, 2679, 2706, 2707, 2708_
_Make Majapahit rank 3_

Content: _Majapahit ideas_, start screen for Indochina, start screen for Indonesia

**Comment by Zephyrum** [comment]
**Indonesia Start Screen**

The glory days of the Majapahit Empire have long ended, but it has not yet seen it's dusk. Quite the contrary, it remains the most powerful state in the region by a large margin. The fierce naval power of the Hindu rulers of Java have granted them victory after victory and a strong control over the archipelago. Yet, they've been seeing a slow decline caused by a general lack of administrative capacity to handle all of their conquests, a problem no entity in the region faced before, for none was quite as successful at conquering as the Majapahit were.

In the Malaccan peninsula, petty states squabbling over the homelands of the long gone Srivijaya have hardened the locals to battle. A distant relative of the old Srivijayan rulers now controls most of the peninsula from Malacca, and a reunification seems inevitable. When it is finished, perhaps the only state in the region with the bite to face the Majapahit shall be created.

As the Great Yuan collapses further North, most of the region is free of Chinese influence, and little is in the way of the rulers of the islands from potential expeditions into the Thai lands. The future looks, at the very least, highly promising for the merchants of the so-called spice islands...

**Comment by Zephyrum** [comment]
**Indochina Start Screen**

Chinese influence has been fading from the region for decades, if not centuries, at this point. The Mongol invasion of China has put the region on the knife's edge, but it remained fairly untouched as the Khagans focused on building their state in the old Middle Kingdom rather than further expansion in the South. The Thai, Khmer and Burmese states can only feel the ripples from the slow collapse, while the direct neighbors and peoples previously conquered by the Chinese have seen a lasting period of independence unlike any before.

The major exception lies in the Viets. The region has been historically contested, with Chinese states invading it every now and then. Surprisingly, it is the periods of stability and internal cohesion in China that have been the safest for the locals, for when governors stop listening to central authority, the Southern ones have a tendency to invade, and this time is no exception.

As the Sixiang reformation spread like a wildfire across China, it could also be felt in Vietnam, particularly the North. This gave the Yue a good reason and local support to launch a swift conquest of the region. Following the fall of the capital of Dai Viet, new states have been birthed further South. Meanwhile, in Burma, the old masters of the region, the Pagan dynasty, have all but disappeared, leaving a power vaccuum to be filled, thus far, by the Ava kingdom.

Surrounded by disarray in India and China, Southeast Asia is in a general state of relative peace when compared to darker times, much like their neighbors to the South, in the vast archipelago that is Indonesia. Petty kingdoms squabble with little long term consequence. But it is times like those that breed the men that shake off the status quo, and all it takes is one monarch being too powerful to shake the world.

**Comment by Zephyrum** [comment]
...Might as well, since I'm a completionist; small and mostly for the sake of avoiding false info screens

**Generic African Start Screen**

Africa is home to far too many natural barriers and latitudinal differences, and as such, it's many regions face very distinct differences in all scopes: religious, ethnical, societal, developmental, and much more. It's a collateral effect of the massive deserts and lushful jungles, alongside mountains, rivers and lakes, that dot the continent.

In the North, the Egyptians face off against the Aq Qoyunlu Turks in what might be the decisive moment of that campaign, while the rest of Mediterranean Africa recovers from the shock of the Imwehheddens and the crusades. Slightly South, several states make a living out of the gold and salt trade, notably Mali and Songhai. In the East, the Horn of Africa is contested by the traditional Axumites and the rising Ethiopians as Egyptian influence wanes, with the Somali states remaining as spectators.

Even further South, the jungles of Kongo serve as home to peoples unspoiled by Christianity or advanced non-tribal societies. The lacustrine states fight each other over the lands of the mysterious, yet long gone, Kitara Empire. And in the Swahili coast, the first Christian converts flock as the rulers of Kilwa all convert to Miaphysitism, butting heads with the local fetishist monarchs and tribes.

**Comment by Zephyrum** [comment]
**Far Eastern Start Screen (Japan/Korea/Jurchen/Siberian)**

With the rising trend of isolationism in Korean politics and a general disconnect between the Jurchens and China ever since the fall of the Early Jin, the states East of Beijing have stayed out of danger zone of Chinese politics, themselves too busy with their own local affairs.

The Koreans are experiencing a golden age of the sciences and arts, but show little interest in rising to prominence on the diplomatic stage. Meanwhile in Japan, petty lords and governors have been skirmishing for power for a while, as the Ashikaga Shoguns fail to assert much authority, and it seems those skirmishes are on the verge of starting a war to shake the archipelago.

**Comment by The-Jerm** [comment]
The glory days of the §YMajapahit Empire§! have long ended, but it has not yet seen it's dusk. Quite the contrary, it remains the most powerful state in the region by a large margin. The fierce naval power of the §YHindu§! rulers of §YJava§! have granted them victory after victory and a strong control over the archipelago. Yet, they've been seeing a slow decline caused by a general lack of administrative capacity to handle all of their conquests, a problem no entity in the region faced before, for none was quite as successful at conquering as the §YMajapahit§! were. \nIn the §YMalaccan Peninsula§!, petty states squabbling over the homelands of the long gone §YSrivijaya§! have hardened the locals to battle. A distant relative of the old §YSrivijayan§! rulers now controls most of the peninsula from §YMalacca§!, and a reunification seems inevitable. When it is finished, perhaps the only state in the region with the bite to face the §YMajapahit§! shall be created. \nAs the §YGreat Yuan§! collapses further North, most of the region is free of §YChinese§! influence, and little is in the way of the rulers of the islands from potential expeditions into the §YThai§! lands. The future looks, at the very least, highly promising for the merchants of the so-called spice islands...

**Comment by The-Jerm** [comment]
§YChinese§! influence has been fading from the region for decades, if not centuries, at this point. The §YMongol§! invasion of §YChina§! has put the region on the knife's edge, but it remained fairly untouched as the §YKhagans§! focused on building their state in the old §YMiddle Kingdom§! rather than further expansion in the South. The §YThai§!, §YKhmer§! and §YBurmese§! states can only feel the ripples from the slow collapse, while the direct neighbors and peoples previously conquered by the §YChinese§! have seen a lasting period of independence unlike any before. \nThe major exception lies in the §YViets§!. The region has been historically contested, with §YChinese§! states invading it every now and then. Surprisingly, it is the periods of stability and internal cohesion in §YChina§! that have been the safest for the locals, for when governors stop listening to central authority, the Southern ones have a tendency to invade, and this time is no exception. \nAs the §YSixiang§! reformation spread like a wildfire across §YChina§!, it could also be felt in §YVietnam§!, particularly the North. This gave the §YYue§! a good reason and local support to launch a swift conquest of the region. Following the fall of the capital of §YDai Viet§!, new states have been birthed further South. Meanwhile, in §YBurma§!, the old masters of the region, the §YPagan§! dynasty, have all but disappeared, leaving a power vacuum to be filled, thus far, by the §YAva Kingdom§!. \nSurrounded by disarray in §YIndia§! and §YChina§!, §YSoutheast Asia§! is in a general state of relative peace when compared to darker times, much like their neighbors to the South, in the vast archipelago that is §YIndonesia§!. Petty kingdoms squabble with little long term consequence. But it is times like those that breed the men that shake off the status quo, and all it takes is one monarch being too powerful to shake the world.

**Comment by The-Jerm** [comment]
§YAfrica§! is home to far too many natural barriers and latitudinal differences, and as such, it's many regions face very distinct differences in all scopes: religious, ethnic, societal, developmental, and much more. It's a collateral effect of the massive deserts and lush jungles, alongside mountains, rivers and lakes, that dot the continent. \nIn the North, the §YEgyptians§! face off against the §YAq Qoyunlu Turks§! in what might be the decisive moment of that campaign, while the rest of §YMediterranean Africa§! recovers from the shock of the §YImwehheddens§! and the crusades. Slightly South, several states make a living out of the gold and salt trade, notably §YMali§! and §YSonghai§!. In the East, the §YHorn of Africa§! is contested by the traditional §YAxumites§! and the rising §YEthiopians§! as §YEgyptian§! influence wanes, with the §YSomali§! states remaining as spectators. \nEven further South, the jungles of §YKongo§! serve as home to peoples unspoiled by §YChristianity§! or advanced non-tribal societies. The lacustrine states fight each other over the lands of the mysterious, yet long gone, §YKitara Empire§!. And in the §YSwahili§! coast, the first §YChristian§! converts flock as the rulers of §YKilwa§! all convert to §YMiaphysitism§!, butting heads with the local fetishist monarchs and tribes.

**Comment by The-Jerm** [comment]
With the rising trend of isolationism in §YKorean§! politics and a general disconnect between the §YJurchens§! and §YChina§! ever since the fall of the §YEarly Jin§!, the states East of §YBeijing§! have stayed out of danger zone of §YChinese§! politics, themselves too busy with their own local affairs. \nThe §YKoreans§! are experiencing a golden age of the sciences and arts, but show little interest in rising to prominence on the diplomatic stage. Meanwhile in §YJapan§!, petty lords and governors have been skirmishing for power for a while, as the §YAshikaga Shoguns§! fail to assert much authority, and it seems those skirmishes are on the verge of starting a war to shake the archipelago. \nRegardless of outcome, all of those areas are bound to see their status quo shaken whenever the looming conflict in §YChina§! sees a final conclusion - if it ever does.
