### ISSUE TITLE
Bugs in Event Chains

### ISSUE THREAD

**Issue by Zephyrum** [Zephyrum/FoI#45]
Northern Chain:
untested still

Southern Chain:
-Second event (for Min) doesn't fire naturally, though effects functional
-It seems none of the "fire in X days" type triggers are working at all
-The declare war options are not actually declaring war
-What in tarnation is this?
https://i.gyazo.com/1a2e79c504a55dcbfe22d0fd82f6f4ab.png
-Wu event has no effect whatsoever in all three options (worth noting in my test game they declared on Min immediately LUL)

Qin Chain:
Clear of problems detected other than being longer to solve than I believed, but functional overall

Sixiang stuff:
-Pulse not set yet

**Comment by neothiamin** [comment]
Re: Southern Chain
1. The Min event is not meant to fire naturally, it is triggered by the first event (the one that gives Yue the core)
2. That's really strange because they should be working fine. The syntax is correct.
3. Check for truces. I think if nations have a truce, a declare_war_with_cb effect does nothing. Thanks paradox.
4. I did that in case none of the other nations accept the coalition. It checks to see how long it's been since foi_south_china.2 fired and then allows the event to fire. Don't worry about it.
5. I'll do that later. I wrote all those other events in a row and needed a breather and then... forgot.

**Comment by Zephyrum** [comment]
1. That's what I mean by naturally, it isn't firing from the Yue one
2. fuck
3. No truces are present
4. I moved the flag to an earlier point to unlock the CB even if they don't take the coalition, so we'll have to figure out an alternative to this, and ideally one faster too
5. alrighty
6. why are you more formal when writing in git

**Comment by CinnamonGamer** [comment]
1.) Bruh
2.) Bruh
3.) Bruh 
4.) Bruh
5.) Bruh
6.) Bruh

**Comment by Zephyrum** [comment]
Closing, let's use the dedicated thread: https://github.com/Zephyrum/FoI/issues/35
